# Generated by Django 2.1.7 on 2019-05-10 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_serialdata_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cardiac_output', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stroke_volume', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estimated_delta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stiffness_index', models.DecimalField(decimal_places=2, max_digits=5)),
                ('augmented_index', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pulse_wave_velocity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
