# Generated by Django 2.1.7 on 2019-05-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_endpoint_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint_check',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
