# Generated by Django 2.1.7 on 2019-05-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_endpoint_check_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='plot',
            field=models.ImageField(default='1', upload_to='graph'),
            preserve_default=False,
        ),
    ]
